workflows:
  android-debug:
    name: JENIL DIAMOND Android APK
    max_build_duration: 30

    environment:
      flutter: stable

    scripts:

      - name: Generate Android project
        script: |
          flutter create --platforms=android .

      - name: Add SMS Permission
        script: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"

          if ! grep -q "android.permission.SEND_SMS" "$MANIFEST"; then
            sed -i.bak '/<application/i\
          <uses-permission android:name="android.permission.SEND_SMS"/>' "$MANIFEST"
          fi

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Fix Telephony Namespace
        script: |
          TELEPHONY_GRADLE="$HOME/.pub-cache/hosted/pub.dev/telephony-0.2.0/android/build.gradle"

          if [ -f "$TELEPHONY_GRADLE" ]; then
            if ! grep -q "namespace" "$TELEPHONY_GRADLE"; then
              sed -i.bak '/android {/a\
              namespace "com.shounakmulay.telephony"
              ' "$TELEPHONY_GRADLE"
            fi
          fi

      - name: Generate App Icon
        script: |
          dart run flutter_launcher_icons

      - name: Generate Splash Screen
        script: |
          dart run flutter_native_splash:create

      - name: Build Android APK
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
